### ISSUE TITLE
/home: Escaping video doesn't work on all devices

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#27]
The X for the video window isn’t visible on certain devices.
Escape doesn’t work to exit

**Comment by ricewithabee** [comment]
Also: video doesn't pause automatically when user exits.

**Comment by ricewithabee** [comment]
Also: clicking above or below the video doesn't exit out.

**Comment by ricewithabee** [comment]
Fixed:

- The X for the video window isn’t visible on certain devices.
- video doesn't pause automatically when user exits.
- clicking above or below the video doesn't exit out.

Partially fixed:
- Escape doesn’t work to exit: ESC now works but only as long as video playback hasn't started. This is because when a YouTube video is playing in an iframe, it captures keyboard events like the ESC key press. Seems to require actual coding skills to get around. @plexish

**Comment by melissasamworth** [comment]
I imagine let's address this in the technical call with nemo. I'll prep for that call by trying to have a good understanding of how to integrate custom code.

**Comment by melissasamworth** [comment]
@ricewithabee could you recenter the X? :)

**Comment by ricewithabee** [comment]
> @ricewithabee could you recenter the X? :)

Done. I made it a little bigger for you too.

**Comment by ricewithabee** [comment]
Will discuss with Nemo next week.

**Comment by melissasamworth** [comment]
Update: Nemo tries quick fix, if it doesn't work forget it (change to low priority)

**Comment by ricewithabee** [comment]
@mruwnik if it's easy enough to do, I think we should make the video automatically start. This will (mostly) avoid this issue, since the user is less likely to click inside the modal (e.g. pressing Start) and therefore won't cause YouTube to start capturing keystrokes. 

Here's an example: https://www.vastspace.com/

**Comment by melissasamworth** [comment]
@ricewithabee yes i wanted this just didn't know how!

**Comment by mruwnik** [comment]
how about now?

**Comment by ricewithabee** [comment]
Yaaass queen 🙏🏼

**Comment by melissasamworth** [comment]
Everything is right in the world. It's like alignment was just solved.
