### ISSUE TITLE
Title -> AISafety.com ?

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#32]
"I think the logo thing in the top corner should be AISafety.com. This logo thing communicates the name of the site. But “AI safety” is the name of the field, not the site. AISafety.com is the name of the site. (“I was on AI safety the other day” doesn’t make sense, whereas “I was on AISafety.com the other day” does)"

**Comment by ricewithabee** [comment]
![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/4528b5c0-a4bf-4564-86da-752fdff88854)

I think this further illustrates why it should be AISafety.com instead of AI safety: When we describe ourselves (the website) it looks like we're describing the field as a whole.

**Comment by melissasamworth** [comment]
Okay, this is a more intuitive kind of thing, but I felt like naming our site AI Safety just felt a lot more powerful than repeating the url of our site. You come to to aisafety.com to for things related to AI Safety. I've also never seen a site call themselves, in their logo, [whatever].com. Dribbble.com is "Dribbble", "medium.com" is medium.

If I'm outvoted here I concede but I would be a bit more convinced if there were some more votes against me.

**Comment by ricewithabee** [comment]
Booking.com and cars.com are a couple examples where I think they chose to have .com in their company name/website logo because without the .com part it would be too generic – it would be confusing for a website to call itself Booking or Cars. I think it's the same deal with AI safety. Just my opinion though, fair enough if others disagree.

**Comment by melissasamworth** [comment]
Update: we'll use AISafety.com
