### ISSUE TITLE
/jobs, /courses, /communities, /funders: include logos in each card

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/AISafety.com#58]
This will make it more engaging and less "wall of texty"

**Comment by melissasamworth** [comment]
@ricewithabee  Agreed this would be nice. As a sidenote I think we may want to consider the dev effort and design effort that go behind these various tasks and prioritize the ones with high value and low effort.

**Comment by ricewithabee** [comment]
I agree it has to be worth the design/dev work, and in this case I'm not sure how much of those it would entail. It just strikes me very hard that as a user the main reason I don't think I would use the current site is because the lists feel like walls of text, which I guess makes it feel inaccessible/overwhelming and somehow less trustworthy as to its accuracy (gives me the feeling that this list isn't being maintained and so is probably stale).

**Comment by ricewithabee** [comment]
@melissasamworth any further thoughts on this? Or @plexish and @soerenelverlin

**Comment by melissasamworth** [comment]
@ricewithabee that's interesting, so signals that the list is maintained are very important, you think? 

This task is definitely non-trivial design/dev wise but perhaps worth it. Firstly though, we need an image column in the Airtables, and for someone to fill that out. We also need to make sure whalesync allows us to bring in images. If all that is doable then let's consider it. 

Current evidence in favor of more thumbnails
- Pretty much every job board ever does this. This means they probably do it for a reason, and also that people have this model for how databases should look.
- Bryce thinks it solves the usability issue of just too much text, and that it is somehow related to being frequently maintained, and thinks he would use the site a lot more as for this
- Worth getting more data from others users...?

**Comment by ricewithabee** [comment]
Yeah, I think a classic issue with resources lists is that the creator often maintains them for a while at the start but then eventually does it less and less, causing the list to lose relevance and accuracy. So signalling that these lists are highly maintained/trustworthy seems valuable. For me that's just one reason in favour of adding logos though remember.

Regarding the image column in Airtable:
- /jobs is easy because we can pull that directly from the 80k Airtable which we already pull everything from
- /courses is easy enough because there aren't many and it's a one off thing to copy them all from their respective websites
- /funders easier because most we already have for aisafety.world
- /communities more challenging, probably need to go into each community Discord/Slack and somehow copy their image from there.

From a quick google it looks like Whalesync won't have a problem with images.

Since this will entail a fair bit of design/dev work, I think it's worth getting impressions from other users to get their thoughts on this first.

**Comment by melissasamworth** [comment]
Okay, yeah if you're willing to do the setup and everything, I'll do the design. Let's see what the others think on the call today

**Comment by ricewithabee** [comment]
Update: top of backburner.

**Comment by ricewithabee** [comment]
Further update: Melissa is keen to do this now

**Comment by ricewithabee** [comment]
@melissasamworth /jobs has images locked and loaded in the CMS for when you want to throw a design at it

**Comment by melissasamworth** [comment]
Update: sorry a bit behind, will show designs tomorrow for review

**Comment by ricewithabee** [comment]
All records in all four databases now have images 👌🏼

**Comment by melissasamworth** [comment]
Great! Designs are done https://www.figma.com/file/I37tnefBooOLBxrP4qVwMN/AI-Safety?type=design&node-id=672%3A3260&mode=design&t=r2AAc2LoUOMPLSH3-1 , will implement them next week
